include_recipe "#{cookbook_name}::apt"
include_recipe "#{cookbook_name}::base"
include_recipe "#{cookbook_name}::www"
#include_recipe "#{cookbook_name}::smtp"
#include_recipe "#{cookbook_name}::imap"
